/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const LoanApplication = IDL.Record({
  'status' : ApplicationStatus,
  'applicantName' : IDL.Text,
  'contactInfo' : IDL.Text,
  'loanAmount' : IDL.Float64,
  'applicationId' : IDL.Nat,
  'income' : IDL.Float64,
  'employmentDetails' : IDL.Text,
  'applicationDate' : IDL.Int,
  'loanPurpose' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteLoanApplication' : IDL.Func([IDL.Nat], [], []),
  'getAllLoanApplications' : IDL.Func(
      [],
      [IDL.Vec(LoanApplication)],
      ['query'],
    ),
  'getApplicationsByStatus' : IDL.Func(
      [ApplicationStatus],
      [IDL.Vec(LoanApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLoanApplicationById' : IDL.Func([IDL.Nat], [LoanApplication], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLoanApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'updateLoanApplication' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const LoanApplication = IDL.Record({
    'status' : ApplicationStatus,
    'applicantName' : IDL.Text,
    'contactInfo' : IDL.Text,
    'loanAmount' : IDL.Float64,
    'applicationId' : IDL.Nat,
    'income' : IDL.Float64,
    'employmentDetails' : IDL.Text,
    'applicationDate' : IDL.Int,
    'loanPurpose' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteLoanApplication' : IDL.Func([IDL.Nat], [], []),
    'getAllLoanApplications' : IDL.Func(
        [],
        [IDL.Vec(LoanApplication)],
        ['query'],
      ),
    'getApplicationsByStatus' : IDL.Func(
        [ApplicationStatus],
        [IDL.Vec(LoanApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLoanApplicationById' : IDL.Func(
        [IDL.Nat],
        [LoanApplication],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLoanApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'updateLoanApplication' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };